// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktjobfsmlaipsetvezwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0am9iZnNtbGFpcHNldHZlendqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MDU3ODEsImV4cCI6MjA3Mzk4MTc4MX0.FzfR2QcmlpA3IEKC5nlIIREm9DAugPmocx1vb3gau9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});